config/routes.rb
Rails.application.routes.draw do
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'

  get 'payments/create'
  get 'payments/create2'

  get 'static_pages/gallery'

  resources :products do
    resources :comments
  end
  
  get 'static_pages/faq'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'welcome/index'

  post 'static_pages/thank_you'

  post 'payments/create'
  post 'payments/create2'

  root 'static_pages#index'

  mount ActionCable.server => '/cable'

  resources :orders, only: [:index, :show, :create, :destroy]

  devise_for :users, controllers: { registrations: "registrations", passwords: "passwords" }, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  resources :users
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :product, touch: true

  validates :body, presence: true
  validates :user, presence: true
  validates :product, presence: true
  validates :rating, numericality: { only_integer: true }

  after_commit { CommentUpdateJob.perform_later(self, @user) }

  scope :rating_desc, -> { order(rating: :desc) }
  scope :rating_asc, -> { order(rating: :asc) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@product = Product.find(params[:product_id])
  	@comment = @product.comments.new(comment_params)
  	@comment.user = current_user
    @user = current_user
    logger.debug("User creating a comment: #{current_user.email }")
    respond_to do |format|
      if @comment.save
        #ActionCable.server.broadcast 'product_channel', comment: @comment, average_rating: @comment.product.average_rating
        #ProductChannel.broadcast_to @product.id, comment: @comment, average_rating: @comment.product.average_rating
        #ProductChannel.broadcast_to @product.id, comment: CommentsController.render(partial: 'comments/comment', locals: {comment: @comment, current_user: current_user}), average_rating: @comment.product.average_rating
        logger.debug("Comment saved successfully!")
        logger.debug("Action cable server- #{ActionCable.server}")
        format.html { redirect_to @product, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @product }
        format.js
      else
        format.html { redirect_to @product, alert: 'Comment was not save successfully.'}
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    product = @comment.product
    @comment.destroy
    redirect_to product
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :body, :rating)
  end


  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <hr>
  <strong><%= comment.user.first_name %></strong> 
  <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
    <% if current_user && current_user.admin? %>
      <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product,comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end%>
    <br>
  <div class="rated" data-score="<%= comment.rating %>"></div>
  <br><%= comment.body %>
</div>

app/views/comments/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
            <p><%= "Rating: #{comment.rating}/5" %></p>
            <p><%= comment.body %></p>
        </div>
    <% end %>
</div>

app/views/comments/_form.html.erb
<% if signed_in? %>
  <h4>Add your review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.label :rating %><br>
      <div class="rating"></div>
    </p>  
    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>

app/views/comments/create.js.erb
$("#new_comment").html("Thank you for your review!");
//$('.product-reviews').prepend("<%= j render @comment %>");
$("#average-rating").attr('data-score', "<%= @product.average_rating %>");
refreshRating();