config/routes.rb
Rails.application.routes.draw do
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'

  get 'payments/create'
  get 'payments/create2'

  get 'static_pages/gallery'

  resources :products do
    resources :comments
  end
  
  get 'static_pages/faq'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'welcome/index'

  post 'static_pages/thank_you'

  post 'payments/create'
  post 'payments/create2'

  root 'static_pages#index'

  mount ActionCable.server => '/cable'

  resources :orders, only: [:index, :show, :create, :destroy]

  devise_for :users, controllers: { registrations: "registrations", passwords: "passwords" }, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  resources :users
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :line_items
	has_many :orders, :through => :line_items
	has_many :comments, dependent: :destroy
	validates :name, presence: true

	def highest_rating_comment
  	comments.rating_desc.first
	end

	def worst_rating_comment
  	comments.rating_asc.first
	end

	def comments_count
		comments.count
	end	

	def average_rating
  	comments.average(:rating).to_f
	end

	def self.search(search_term)
		where(" lower(name) LIKE lower(?) ", "%#{search_term}%")
	end

	def score
		$redis.zincrby("the_popular_product", 1, self.id)
	end

	def self.top 
		 $redis.zrevrange("the_popular_product", 0, 0).map{|id| Product.find(id)}
		 
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term= params[:q]
      @products = Product.search(search_term)
      #@products = Product.where(" lower(name) LIKE lower(?) ", "%#{search_term}%")
    else
      @products = Product.all
    end
    
      @top_product = Product.top
    
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.paginate(:page => params[:page], :per_page => 2).order("created_at DESC")
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    #byebug
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :flower_colour, :price, :quantity)
    end

    def expire_cache
      ActionController::Base.new.expire_fragment(cache_key_for_products)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
	def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <%= render partial: "comments/comment", locals: {comment: comment} %>
    <% end %>
</div>
<%= will_paginate @comments %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :flower_color %><br>
    <%= f.text_field :flower_colour, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity, class: 'form-control' %>
  </div>

</div>
  <div class="actions">
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="col-sm-6  col-md-3">
  <div class="product_image">
    <% cache product do %>
      <% logger.debug "Product image is there: #{product.image_url}"%>
            
        <%= image_tag(product.image_url, class: "img-responsive") %>
        <h4><%= product.name %></h4>
        <p><%= product.description %></p>
        
        
        <strong>Price: &pound;<%= product.price.to_f %></strong>
            
        <strong> In stock: 
          <% if product.quantity > 0 %>
            <%= "yes" %>
          <% else %>
              <%= "no" %>
          <% end %>
        </strong>
        
        <strong> Created: <%=product.created_at.to_formatted_s(:long) %> </strong>
    <% end %>  
    <% if ( (@top_product!= nil) && (@top_product[0].id == product.id)) %>  
      <p id="top_product">The most popuar product!</p>
    <% end %>  
        
    <%= link_to 'Show', product %>
    <% if signed_in? && current_user.admin? %>
      <%= link_to 'Edit', edit_product_path(product) %>
      <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
      
  </div>
</div><!-- /col -->

app/views/products/edit.html.erb
<div class="product_show_page">

	<h1>Editing Product</h1>

	<%= render 'form' %>

	<div class="product_link">
		<%= link_to 'Show', @product %>|
		<%= link_to 'Back', products_path %>
		<%= link_to 'Home', static_pages_index_path %>
		<%= link_to 'Gallery', '/static_pages/gallery' %>
	</div>

</div>

app/views/products/index.html.erb
<div class="shop_pages">
  <p id="notice"><%= notice %></p>

  <h1>Cacti for sale</h1>
<div class="container">
  <%= form_tag "/products", method: "get", class: 'navbar-form navbar-left' do %>
    <div class="form-group">
        <%= text_field_tag :q, nil, class: 'form-control', placeholder: 'Search by name' %>
    </div>
        <%= submit_tag "Search", class: "btn btn-default" %>
    <% end %>
    <% unless signed_in? %>
      <div class="product_link">
        To buy plants please login.
      </div>
    <% end %>
  <% if signed_in? && current_user.admin? %>
    <div class="product_link">
      <%= link_to 'New Product', new_product_path %>
    </div>
  <% end %>
  </div>

  <div class="container">
    <div class="row">
     
      <% #cache(cache_key_for_products) do %>
        <%= render @products %>
      <% #end %>
    </div>
  </div>
  

</div>

app/views/products/new.html.erb
<div class="product_pages">
	<h1>New Product</h1>

	<%= render 'form' %>

	<div class="product_link">
		<%= link_to 'Back', :back %> <%= link_to 'Shop', products_path %>
	</div>
</div>

app/views/products/show.html.erb
<div class="product_show_page">
  <p id="notice"><%= notice %></p>

  <div class="container-fluid">
    <% cache @product do %>
      <h1><%= @product.name %></h1>
    <%# end %>
      <div class="row" data-product-id="<%= @product.id %>">
      
      
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            
              <%= image_tag(@product.image_url, class: "img-responsive img-zoom", data_zoom_image: @product.image_url) %>
            
            <div class="caption product_show">
              <%# cache @product do %>
                <h1><%= @product.name %></h1>
                <p>
                  <strong>Price:</strong> £<%= @product.price %>
                </p>
              <% end %>
              <p>
                <strong>Quantity: </strong> <%= @product.quantity %>
              </p>
              <p>
                <% if (@product.quantity > 0) && signed_in? %>
                  <a class="btn btn-success" href='/cart/<%= @product.id %>'>Add to cart</a>

                    <%#= form_tag "/payments/create" do %>
                      <%#= hidden_field_tag(:product_id, @product.id) %>
                      <%#= render partial: "shared/stripe_checkout_button" %>
                    <% #end %>
                <% end %>

              <% if signed_in? && current_user.admin? %>
                <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-success"  %> 
              <% end %>
                <%= link_to 'Back', products_path, class: "btn btn-success" %>
                
              </p>
            </div>
          </div>
        </div>

        <div class="col-sm-6 col-md-4">
          

            <p class="product_show">
              <strong>Creation date: </strong>
              <%= @product.created_at.to_formatted_s(:long) %>
            </p>

            <p class="product_show">
              <strong>In stock: </strong>
              <% if (@product.quantity > 0) %>
                <%= " yes" %>
              <% else %>
                <%= " no" %>
              <% end %>
            </p>
            
            <p class="product_show">
              <strong>Description: </strong><%= @product.description %> 
            </p>
            <p class="product_show">
                <strong>Flower color: </strong> <%= @product.flower_colour %> 
            </p>

        

          <p class="product_show">
          <% if @product.comments_count >0 %>
            <strong>Average Rating:</strong>
            <div  id= "average-rating" class="rated" data-score="<%= @product.average_rating %>"></div> 
            <br>
              <strong>Top positive review:</strong>
              <div id="highest_rating_text"><%= @product.highest_rating_comment.body %></div>
              <br>
              <strong>Top critical review:</strong>
              <div id="worst_rating_text"><%= @product.worst_rating_comment.body %></div>
          <% else %>
              <strong>No comments for this product.</strong>
          <% end %>

          </p>
          <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
          Customer Reviews <%= render 'comments' %>
        </div>

        <div class="col-sm-6 col-md-4">
          <%= render 'comments/form' %>
        </div>


        

      </div>
    
  </div>

</div>
	