config/routes.rb
Rails.application.routes.draw do
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'

  get 'payments/create'
  get 'payments/create2'

  get 'static_pages/gallery'

  resources :products do
    resources :comments
  end
  
  get 'static_pages/faq'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'welcome/index'

  post 'static_pages/thank_you'

  post 'payments/create'
  post 'payments/create2'

  root 'static_pages#index'

  mount ActionCable.server => '/cable'

  resources :orders, only: [:index, :show, :create, :destroy]

  devise_for :users, controllers: { registrations: "registrations", passwords: "passwords" }, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFirstRailsApp</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
    <link rel="stylesheet" href="css/bootstrap-image-gallery.min.css">

    
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'false' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'false' %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'jquery.raty.js' %>
    
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="page-wrap">

      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
        	 <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
              <%= image_tag("Acantocalycium_violaceum.jpg", class: "img-responsive", width: '50') %>
            </a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
    	       <li><%= link_to 'Home', static_pages_index_path %></li>
    	       <li><%= link_to 'About', static_pages_index_path(:anchor => "about") %></li>
    	       <li><%= link_to 'Gallery', static_pages_gallery_path %></li>
    	       <li><a href="https://cactus-blog.herokuapp.com/">Blog</a></li>
    	       <li><%= link_to 'Shop', products_path %></li>
             <li><%= link_to 'FAQ', static_pages_faq_path %></li>
    	       <li><%= link_to 'Contact', static_pages_contact_path %></li>
            </ul>
            <ul class="nav pull-left">
            <% if user_signed_in? %>
            <li>
              <div class="hello_user">Hi, <%= current_user.first_name %></div>
            </li>
            <% end %>
            <li>
              <% if user_signed_in? %>
                
                <%= link_to('Logout',destroy_user_session_path, :method => :delete, class: "login_link") %>
                
              <% else %>
                <%= link_to('Login', new_user_session_path, class: "login_link") %>
              <% end %>
            </li>
            </ul>
            <!--<form class="navbar-form navbar-left">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form>-->
            
          </div>
        </div>
      </nav>

      <!-- devise tags -->
      <% if alert %>
      <p class="alert alert-warning"><%= alert %></p>
      <% end %>
      
      <%#=image_tag("cacti-bg.jpg", width: "100%", alt: "Cacti in a desert")%>

      <%= yield %>
              
      <footer class="site-footer">
       &copy; 2016 Julia's cactus site
      </footer>

    </div>
  </body>
</html>